---  # mkdocs.yml

site_name: Solutions informatiques durables
site_url: http://localhost:8000/mysite
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: deep orange
  logo: assets/microlinux-logo.png
  favicon: assets/favicon.png
  font:
    text: Red Hat Text
    code: Red Hat Mono
  language: fr
  features:
    # When instant loading is enabled, clicks on all internal links will be
    # intercepted and dispatched via XHR without fully reloading the page.
    - navigation.instant
    # When anchor tracking is enabled, the URL in the address bar is
    # automatically updated with the active anchor as highlighted in the table
    # of contents.
    - navigation.tracking
    # When tabs are enabled, top-level sections are rendered in a menu layer
    # below the header for viewports above 1220px, but remain as-is on mobile.
    - navigation.tabs
    # A back-to-top button can be shown when the user, after scrolling down,
    # starts to scroll up again. It's rendered centered and just below the
    # header.
    - navigation.top
extra_css:
  - css/extra.css
plugins:
  - privacy
copyright: >
  Copyright &copy; 2025 Nicolas Kovacs –
  <a href="#__consent">Modifier le paramétrage des cookies</a>

...
