---  # mkdocs.yml

site_name: Solutions informatiques durables
site_url: http://localhost:8000/mysite
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: deep orange
  logo: assets/microlinux-logo.png
  favicon: assets/favicon.png
  font:
    text: Red Hat Text
    code: Red Hat Mono
  language: fr

extra_css:
  - css/extra.css
plugins:
  - social

...
